version: '3.9'

services:
  bot:
    build: .
    container_name: sr-dashboard-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      TWELVEDATA_KEY: ${TWELVEDATA_KEY}
    restart: always
